import type { Metadata } from 'next'
import { Cardo } from 'next/font/google'
import localFont from 'next/font/local'
import './globals.css'
import { SpeedInsights } from '@vercel/speed-insights/next'

// const geistSans = localFont({
//   src: './fonts/GeistVF.woff',
//   variable: '--font-geist-sans',
//   weight: '100 900',
// })
// const geistMono = localFont({
//   src: './fonts/GeistMonoVF.woff',
//   variable: '--font-geist-mono',
//   weight: '100 900',
// })

const cardo = Cardo({
  weight: '400',
  style: 'normal',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-cardo',
})

const wotfard = localFont({
  src: './fonts/wotfard-regular-webfont.woff2',
})

export const metadata: Metadata = {
  title: 'Sameh Hamdi',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${wotfard.className} ${cardo.variable} text-foreground antialiased`}
      >
        {children}
        <SpeedInsights />
      </body>
    </html>
  )
}
