import type { Metadata } from 'next'
import { Domine, Nunito } from 'next/font/google'
import './globals.css'
import { SpeedInsights } from '@vercel/speed-insights/next'

const domine = Domine({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-domine',
})

const nunito = Nunito({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Sameh Hamdi',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.className} ${domine.variable} antialiased`}>
        {children}
        <SpeedInsights />
      </body>
    </html>
  )
}
