import type { Metadata } from "next"
import { Inter, Lora } from "next/font/google"

import "@/styles/globals.css"

import { ThemeProvider } from "@/providers/theme-provider"

import Header from "@/components/header"
import SiteFooter from "@/components/site-footer"
import TailwindIndicator from "@/components/tailwind-indicator"

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
})
const lora = Lora({
  subsets: ["latin"],
  variable: "--font-lora",
  display: "swap",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${lora.variable}`}
      suppressHydrationWarning
    >
      <body className="min-h-screen bg-background text-foreground antialiased">
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem={false}
        >
          <Header />
          <main>{children}</main>
          <TailwindIndicator />
          <SiteFooter />
        </ThemeProvider>
      </body>
    </html>
  )
}
